# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [44]:
import numpy as np

#### 2. Print your NumPy version.

In [45]:
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [46]:
a=np.random.rand(2,3,5)
a

array([[[0.14608064, 0.35742795, 0.4823327 , 0.91435777, 0.15806348],
        [0.94523112, 0.45878945, 0.75610261, 0.62940877, 0.38619521],
        [0.39392211, 0.35527998, 0.13130763, 0.44322237, 0.44018187]],

       [[0.58013071, 0.35870736, 0.24747152, 0.61572553, 0.40721392],
        [0.10601934, 0.42301899, 0.235388  , 0.24323322, 0.45110478],
        [0.43036463, 0.21915012, 0.25143974, 0.61935852, 0.65638166]]])

In [47]:
np.random.random_integers(10, size=(2,3,5))

C:\Users\osile\AppData\Local\Temp\ipykernel_7444\647403137.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  np.random.random_integers(10, size=(2,3,5))


array([[[ 6, 10,  8,  8,  4],
        [ 9,  9,  5,  4,  5],
        [ 6,  4,  6,  3,  3]],

       [[ 3, 10,  1,  5,  1],
        [ 4,  2,  2,  9,  2],
        [ 3,  5,  9,  9,  5]]])

In [48]:
R3=np.random.randn(2,3,5)
R3

array([[[ 2.48433251,  0.21207614, -0.83699436,  0.95179626,
         -0.14561516],
        [-0.9602489 ,  0.25946738, -0.82291245,  1.33100416,
         -0.04603204],
        [-0.03081788, -0.1282471 ,  0.56250889, -1.75319084,
          1.48501642]],

       [[-0.30439357, -0.14424002, -0.34796603,  0.37920142,
         -0.42534755],
        [-0.23439249,  0.88867008,  0.68256947, -0.29609843,
          1.24187778],
        [ 2.28507711, -0.04527445,  1.66025814,  0.91667732,
          0.42910658]]])

#### 4. Print *a*.


In [49]:
print(a)

[[[0.14608064 0.35742795 0.4823327  0.91435777 0.15806348]
  [0.94523112 0.45878945 0.75610261 0.62940877 0.38619521]
  [0.39392211 0.35527998 0.13130763 0.44322237 0.44018187]]

 [[0.58013071 0.35870736 0.24747152 0.61572553 0.40721392]
  [0.10601934 0.42301899 0.235388   0.24323322 0.45110478]
  [0.43036463 0.21915012 0.25143974 0.61935852 0.65638166]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [50]:
import numpy as np

b=np.ones((5, 2, 3), dtype=int)
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [51]:
a.shape

(2, 3, 5)

#### 6. Print *b*.

In [52]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [53]:
#yes
if b is a:
    print(True)
else:
    print(False)


False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [54]:
print(a,b)

[[[0.14608064 0.35742795 0.4823327  0.91435777 0.15806348]
  [0.94523112 0.45878945 0.75610261 0.62940877 0.38619521]
  [0.39392211 0.35527998 0.13130763 0.44322237 0.44018187]]

 [[0.58013071 0.35870736 0.24747152 0.61572553 0.40721392]
  [0.10601934 0.42301899 0.235388   0.24323322 0.45110478]
  [0.43036463 0.21915012 0.25143974 0.61935852 0.65638166]]] [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [55]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
#No they are not the same type nor shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [56]:
c=np.transpose(b, axes=(1,2,0)) 
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [57]:
c.shape

(2, 3, 5)

# 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [58]:
d=(np.add(a,c))
print(d)

[[[1.14608064 1.35742795 1.4823327  1.91435777 1.15806348]
  [1.94523112 1.45878945 1.75610261 1.62940877 1.38619521]
  [1.39392211 1.35527998 1.13130763 1.44322237 1.44018187]]

 [[1.58013071 1.35870736 1.24747152 1.61572553 1.40721392]
  [1.10601934 1.42301899 1.235388   1.24323322 1.45110478]
  [1.43036463 1.21915012 1.25143974 1.61935852 1.65638166]]]


In [59]:
#yes it worked,the shapes of the arrays the same

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [60]:
print(a ),(d)

[[[0.14608064 0.35742795 0.4823327  0.91435777 0.15806348]
  [0.94523112 0.45878945 0.75610261 0.62940877 0.38619521]
  [0.39392211 0.35527998 0.13130763 0.44322237 0.44018187]]

 [[0.58013071 0.35870736 0.24747152 0.61572553 0.40721392]
  [0.10601934 0.42301899 0.235388   0.24323322 0.45110478]
  [0.43036463 0.21915012 0.25143974 0.61935852 0.65638166]]]


(None,
 array([[[1.14608064, 1.35742795, 1.4823327 , 1.91435777, 1.15806348],
         [1.94523112, 1.45878945, 1.75610261, 1.62940877, 1.38619521],
         [1.39392211, 1.35527998, 1.13130763, 1.44322237, 1.44018187]],
 
        [[1.58013071, 1.35870736, 1.24747152, 1.61572553, 1.40721392],
         [1.10601934, 1.42301899, 1.235388  , 1.24323322, 1.45110478],
         [1.43036463, 1.21915012, 1.25143974, 1.61935852, 1.65638166]]]))

In [61]:
#they both have the same shape but different elemements

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [62]:
print(a)

print(c)

[[[0.14608064 0.35742795 0.4823327  0.91435777 0.15806348]
  [0.94523112 0.45878945 0.75610261 0.62940877 0.38619521]
  [0.39392211 0.35527998 0.13130763 0.44322237 0.44018187]]

 [[0.58013071 0.35870736 0.24747152 0.61572553 0.40721392]
  [0.10601934 0.42301899 0.235388   0.24323322 0.45110478]
  [0.43036463 0.21915012 0.25143974 0.61935852 0.65638166]]]
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [74]:
e=print(np.multiply(a, c))

[[[0.14608064 0.35742795 0.4823327  0.91435777 0.15806348]
  [0.94523112 0.45878945 0.75610261 0.62940877 0.38619521]
  [0.39392211 0.35527998 0.13130763 0.44322237 0.44018187]]

 [[0.58013071 0.35870736 0.24747152 0.61572553 0.40721392]
  [0.10601934 0.42301899 0.235388   0.24323322 0.45110478]
  [0.43036463 0.21915012 0.25143974 0.61935852 0.65638166]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# yes e = a

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [75]:
print(d)

[[[1.14608064 1.35742795 1.4823327  1.91435777 1.15806348]
  [1.94523112 1.45878945 1.75610261 1.62940877 1.38619521]
  [1.39392211 1.35527998 1.13130763 1.44322237 1.44018187]]

 [[1.58013071 1.35870736 1.24747152 1.61572553 1.40721392]
  [1.10601934 1.42301899 1.235388   1.24323322 1.45110478]
  [1.43036463 1.21915012 1.25143974 1.61935852 1.65638166]]]


In [76]:
d_max=(np.max(d))
print(d_max)

1.945231122830155


In [77]:
d_min=(np.min(d))
print(d_min)

1.1060193359677146


In [78]:
d_mean=(np.mean(d))
print(d_mean)

1.4280870561654384


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [79]:
d

array([[[1.14608064, 1.35742795, 1.4823327 , 1.91435777, 1.15806348],
        [1.94523112, 1.45878945, 1.75610261, 1.62940877, 1.38619521],
        [1.39392211, 1.35527998, 1.13130763, 1.44322237, 1.44018187]],

       [[1.58013071, 1.35870736, 1.24747152, 1.61572553, 1.40721392],
        [1.10601934, 1.42301899, 1.235388  , 1.24323322, 1.45110478],
        [1.43036463, 1.21915012, 1.25143974, 1.61935852, 1.65638166]]])

In [97]:
f=np.empty([2,3,5])
print(f)

[[[1.14608064 1.35742795 1.4823327  1.91435777 1.15806348]
  [1.94523112 1.45878945 1.75610261 1.62940877 1.38619521]
  [1.39392211 1.35527998 1.13130763 1.44322237 1.44018187]]

 [[1.58013071 1.35870736 1.24747152 1.61572553 1.40721392]
  [1.10601934 1.42301899 1.235388   1.24323322 1.45110478]
  [1.43036463 1.21915012 1.25143974 1.61935852 1.65638166]]]


In [98]:
f.shape

(2, 3, 5)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [99]:
f = np.array((d))
f

array([[[1.14608064, 1.35742795, 1.4823327 , 1.91435777, 1.15806348],
        [1.94523112, 1.45878945, 1.75610261, 1.62940877, 1.38619521],
        [1.39392211, 1.35527998, 1.13130763, 1.44322237, 1.44018187]],

       [[1.58013071, 1.35870736, 1.24747152, 1.61572553, 1.40721392],
        [1.10601934, 1.42301899, 1.235388  , 1.24323322, 1.45110478],
        [1.43036463, 1.21915012, 1.25143974, 1.61935852, 1.65638166]]])

In [100]:
a=np.where((f>d_min)&(f<d_mean),25,f)
b=np.where((f>d_mean)&(f<d_max),75,a)
c=np.where((f==d_mean),50,b)
d=np.where((f==d_min),0,c)
e=np.where((f==d_max),100,d)
print(e)

[[[ 25.  25.  75.  75.  25.]
  [100.  75.  75.  75.  25.]
  [ 25.  25.  25.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [  0.  25.  25.  25.  75.]
  [ 75.  25.  25.  75.  75.]]]


In [101]:
f=e
f

array([[[ 25.,  25.,  75.,  75.,  25.],
        [100.,  75.,  75.,  75.,  25.],
        [ 25.,  25.,  25.,  75.,  75.]],

       [[ 75.,  25.,  25.,  75.,  25.],
        [  0.,  25.,  25.,  25.,  75.],
        [ 75.,  25.,  25.,  75.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [87]:
print(d)

[[[1.14608064 1.35742795 1.4823327  1.91435777 1.15806348]
  [1.94523112 1.45878945 1.75610261 1.62940877 1.38619521]
  [1.39392211 1.35527998 1.13130763 1.44322237 1.44018187]]

 [[1.58013071 1.35870736 1.24747152 1.61572553 1.40721392]
  [1.10601934 1.42301899 1.235388   1.24323322 1.45110478]
  [1.43036463 1.21915012 1.25143974 1.61935852 1.65638166]]]


In [102]:
print(f)

[[[ 25.  25.  75.  75.  25.]
  [100.  75.  75.  75.  25.]
  [ 25.  25.  25.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [  0.  25.  25.  25.  75.]
  [ 75.  25.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [82]:
d

array([[[1.14608064, 1.35742795, 1.4823327 , 1.91435777, 1.15806348],
        [1.94523112, 1.45878945, 1.75610261, 1.62940877, 1.38619521],
        [1.39392211, 1.35527998, 1.13130763, 1.44322237, 1.44018187]],

       [[1.58013071, 1.35870736, 1.24747152, 1.61572553, 1.40721392],
        [1.10601934, 1.42301899, 1.235388  , 1.24323322, 1.45110478],
        [1.43036463, 1.21915012, 1.25143974, 1.61935852, 1.65638166]]])

In [85]:
i=np.where((d>d_min)&(d<d_mean),"A",d)
j=np.where((d>d_mean)&(d<d_max),"B",i)
k=np.where((d==d_mean),"C",j)
l=np.where((d==d_min),"D",k)
m=np.where((d==d_max),"E",l)
print(m)

[[['A' 'A' 'B' 'B' 'A']
  ['E' 'B' 'B' 'B' 'A']
  ['A' 'A' 'A' 'B' 'B']]

 [['B' 'A' 'A' 'B' 'A']
  ['D' 'A' 'A' 'A' 'B']
  ['B' 'A' 'A' 'B' 'B']]]
